name: Makefile CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
#     - name: Login to Docker Hub
#       uses: docker/login-action@v1
#       with:
#         username: ${{ secrets.DOCKER_HUB_USERNAME }}
#         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
#     - name: configure
#       run: ./configure

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17.0'
    - run: go version
      
    - name: Install Dependencies
      run: make
      
    - name: Run Buildpack Tests
      run: make tests
      
    - name: Make Builder
      run: make builder
      
    - name: Make Test Images
      run: make test-images 
      
    - name: Run Smoke Tests
      run: make smoke-test
      
#     - name: Build and Publish
#       run: make publish
