name: Makefile CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    # Setup
    - uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Login to GCR
      uses: docker/login-action@v1
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCR_JSON_KEY }}

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17.0'
    - run: go version
    
    # Build
    - name: Install Dependencies
      run: make
      
    - name: Run Buildpack Tests
      run: make tests
      
    - name: Make Builder
      run: make builder
      
    # Test
    - name: Make Test Images
      run: make test-images 
      
    - name: Run Smoke Tests
      run: make smoke-test
      
      
    # Publish
#     - name: Build and Publish
#       run: make publish
