name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

#     - name: Registry Login
#       run: docker login -u _json_key --password-stdin "https://us.gcr.io" < ${secrets.GCLOUD_SERVICE_KEY_FILE} && docker login -u "${secrets.DOCKER_HUB_USERNAME}" --password-stdin <<< "${secrets.DOCKER_HUB_PASSWORD}"
#       shell: bash

    
#     - name: Login to Docker Hub
#       uses: docker/login-action@v1
#       with:
#         username: ${{ secrets.DOCKER_HUB_USERNAME }}
#         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17.0'
    - run: go version

#    - name: Invoker tests
#      run: make invoker-tests

    - name: Buildpack Tests
      run: make buildpack-tests
      
    - name: Make Builder
      run: make builder
      
    - name: Run Smoke Tests
      run: make smoke-test
      
#     - name: Build and Publish
#       run: make publish
